waypoints:
  - name: CRWPDoor
    frame_id: map
    pose:
      position:
        x: 11.75725313
        y: -8.39831832
        z: 0.000
      orientation:
        x: 0.000000
        y: 0.000000
        z: -0.71694844
        w: 0.697126196
  - name: CRWP1
    frame_id: map
    pose:
      position:
        x: 13.31693455
        y: -10.9581594
        z: 0.000
      orientation:
        x: 0.000000
        y: 0.000000
        z: 0.999609118
        w: 0.027957305
  - name: CRWP2
    frame_id: map
    pose:
      position:
        x: 4.990105137
        y: -10.5010223
        z: 0.000000
      orientation:
        x: 0.000000
        y: 0.000000
        z: -0.00604596
        w: 0.999981723
  - name: CRWP3
    frame_id: map
    pose:
      position:
        x: 13.26109089
        y: -10.9919601
        z: 0.00000
      orientation:
        x: 0.000000
        y: 0.000000
        z: 0.693065382
        w: 0.720874729
  - name: CRWP4
    frame_id: map
    pose:
      position:
        x: 13.36628431
        y: -8.97447877
        z: 0.00000
      orientation:
        x: 0.000000
        y: 0.000000
        z: 0.994218645
        w: 0.107374511
  - name: CRWP5
    frame_id: map
    pose:
      position:
        x: 5.165288825
        y: -8.42092451
        z: 0.00000
      orientation:
        x: 0.000000
        y: 0.000000
        z: -0.71949950
        w: 0.694492960
  - name: CRWP6
    frame_id: map
    pose:
      position:
        x: 5.006249880
        y: -10.5385566
        z: 0.00000
      orientation:
        x: 0.000000
        y: 0.000000
        z: -0.01615698
        w: 0.999869467
  - name: CRWP7
    frame_id: map
    pose:
      position:
        x: 13.38604565
        y: -10.9255300
        z: 0.00000
      orientation:
        x: 0.000000
        y: 0.000000
        z: -0.72770481
        w: 0.685890445
  - name: CRWP8
    frame_id: map
    pose:
      position:
        x: 13.25302822
        y: -13.1493526
        z: 0.00000
      orientation:
        x: 0.000000
        y: 0.000000
        z: 0.999952480
        w: 0.009748689
  - name: CRWP9
    frame_id: map
    pose:
      position:
        x: 4.983972095
        y: -12.6844433
        z: 0.00000
      orientation:
        x: 0.000000
        y: 0.000000
        z: 0.704523238
        w: 0.709680919
  - name: CRWP10
    frame_id: map
    pose:
      position:
        x: 5.172140779
        y: -8.27040611
        z: 0.00000
      orientation:
        x: 0.000000
        y: 0.000000
        z: 0.051826561
        w: 0.998656101
  - name: chargingpos
    frame_id: map
    pose:
      position:
        x: 11.67825515
        y: -8.72460928
        z: 0.00000
      orientation:
        x: 0.000000
        y: 0.000000
        z: 0.698470123
        w: 0.715639215

trajectories:
  - name: CRTRAJ1
    waypoints:
    - CRWP4
    - CRWP5
    - CRWP6
    - CRWP7
    - CRWP8
    - CRWP9
    - CRWP10
    - CRWP3
  

