waypoints:
  - name: name1
    frame_id: map
    pose:
      position:
        x: -4.008664
        y: -0.143636
        z: 0.001389
      orientation:
        x: 0.000000
        y: 0.000000
        z: -0.034206
        w: 0.999415
  - name: name2
    frame_id: map
    pose:
      position:
        x: -1.012974
        y: -0.348935
        z: 0.001383
      orientation:
        x: 0.000000
        y: 0.000000
        z: -0.129892
        w: 0.991528
  - name: name3
    frame_id: map
    pose:
      position:
        x: 2.419217
        y: -1.263885
        z: 0.003749
      orientation:
        x: 0.000000
        y: 0.000000
        z: -0.498123
        w: 0.867107
  - name: name4
    frame_id: map
    pose:
      position:
        x: 1.016814
        y: 1.141024
        z: -0.000719
      orientation:
        x: 0.000000
        y: 0.000000
        z: 0.085135
        w: 0.996369
  - name: name5
    frame_id: map
    pose:
      position:
        x: -0.981552
        y: 0.797009
        z: 0.000360
      orientation:
        x: 0.000000
        y: 0.000000
        z: 0.120940
        w: 0.992660
  - name: name6
    frame_id: map
    pose:
      position:
        x: -2.993073
        y: 0.299479
        z: 0.003820
      orientation:
        x: 0.000000
        y: 0.000000
        z: 0.000000
        w: 1.000000
trajectories:
  - name: goto_pos1
    waypoints:
    - name1
    - name2
    - name3
